const {
  SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder,
  ButtonStyle, PermissionFlagsBits, AttachmentBuilder, MessageFlags,
} = require('discord.js');
const fs = require('fs');
const path = require('path');
const config = require('../../config.json');

const invitesPath = path.join(__dirname, '..', '..', 'data', 'invites.json');
const accessPath  = path.join(__dirname, '..', '..', 'data', 'inviteTrackerAccess.json');

function readInvites() { try { return JSON.parse(fs.readFileSync(invitesPath, 'utf8')); } catch { return {}; } }
function readAccess()  { try { return JSON.parse(fs.readFileSync(accessPath,  'utf8')); } catch { return {}; } }
function writeAccess(d) { fs.writeFileSync(accessPath, JSON.stringify(d, null, 2)); }

function inviterStats(invites, userId) {
  const entries = Object.values(invites).filter(e => e.inviterId === userId);
  return {
    total:    entries.length,
    retained: entries.filter(e => e.retained).length,
    lost:     entries.filter(e => e.leftAt && !e.retained).length,
    pending:  entries.filter(e => !e.retained && !e.leftAt).length,
  };
}

module.exports = {
  data: new SlashCommandBuilder()
    .setName('invite-admin')
    .setDescription('Invite tracker management.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
    .addSubcommandGroup(g => g
      .setName('access')
      .setDescription('Manage tracker access')
      .addSubcommand(s => s
        .setName('add')
        .setDescription('Grant a user access to view their own invite stats')
        .addUserOption(o => o.setName('user').setDescription('User to grant').setRequired(true)))
      .addSubcommand(s => s
        .setName('remove')
        .setDescription('Revoke tracker access from a user')
        .addUserOption(o => o.setName('user').setDescription('User to revoke').setRequired(true)))
      .addSubcommand(s => s
        .setName('list')
        .setDescription('List all users with granted tracker access')))
    .addSubcommand(s => s
      .setName('stats')
      .setDescription('View invite stats for a user or server-wide totals')
      .addUserOption(o => o.setName('user').setDescription('User to view (blank = server totals)').setRequired(false)))
    .addSubcommand(s => s
      .setName('reset')
      .setDescription('Clear all tracked invites generated by a user')
      .addUserOption(o => o.setName('user').setDescription('User to reset').setRequired(true)))
    .addSubcommand(s => s
      .setName('export')
      .setDescription('Download invites.json as a file attachment')),

  async execute(interaction) {
    const sub   = interaction.options.getSubcommand(false);
    const group = interaction.options.getSubcommandGroup(false);
    const invites = readInvites();

    // ── access add ───────────────────────────────────────────────
    if (group === 'access' && sub === 'add') {
      const target = interaction.options.getUser('user');
      const access = readAccess();
      access[target.id] = { grantedBy: interaction.user.id, grantedAt: new Date().toISOString() };
      writeAccess(access);
      return interaction.reply({ content: `✅ Tracker access granted to <@${target.id}>.`, flags: MessageFlags.Ephemeral });
    }

    // ── access remove ────────────────────────────────────────────
    if (group === 'access' && sub === 'remove') {
      const target = interaction.options.getUser('user');
      const access = readAccess();
      delete access[target.id];
      writeAccess(access);
      return interaction.reply({ content: `✅ Tracker access revoked from <@${target.id}>.`, flags: MessageFlags.Ephemeral });
    }

    // ── access list ──────────────────────────────────────────────
    if (group === 'access' && sub === 'list') {
      const access = readAccess();
      const entries = Object.entries(access);
      const desc = entries.length > 0
        ? entries.map(([id, d]) =>
            `<@${id}> — granted by <@${d.grantedBy}> <t:${Math.floor(new Date(d.grantedAt).getTime() / 1000)}:R>`
          ).join('\n')
        : 'No users have been granted access.';
      const embed = new EmbedBuilder()
        .setColor(config.colors.info)
        .setTitle('📋 Invite Tracker Access List')
        .setDescription(desc)
        .setTimestamp();
      return interaction.reply({ embeds: [embed], flags: MessageFlags.Ephemeral });
    }

    // ── stats ────────────────────────────────────────────────────
    if (sub === 'stats') {
      const target = interaction.options.getUser('user');

      if (target) {
        const s = inviterStats(invites, target.id);
        const embed = new EmbedBuilder()
          .setColor(config.colors.info)
          .setTitle(`📊 Invite Stats — ${target.tag}`)
          .setThumbnail(target.displayAvatarURL())
          .addFields(
            { name: '📨 Total Invites', value: `${s.total}`,    inline: true },
            { name: '✅ Retained (30d)', value: `${s.retained}`, inline: true },
            { name: '⏳ Pending',        value: `${s.pending}`,  inline: true },
            { name: '❌ Lost',           value: `${s.lost}`,     inline: true },
          )
          .setTimestamp();
        return interaction.reply({ embeds: [embed], flags: MessageFlags.Ephemeral });
      }

      // Server-wide
      const all = Object.values(invites);
      const inviterMap = {};
      for (const e of all) {
        if (!inviterMap[e.inviterId]) {
          inviterMap[e.inviterId] = { username: e.inviterUsername, retained: 0 };
        }
        if (e.retained) inviterMap[e.inviterId].retained++;
      }
      const top5 = Object.entries(inviterMap)
        .sort(([, a], [, b]) => b.retained - a.retained)
        .slice(0, 5)
        .map(([id, d], i) => `${i + 1}. <@${id}> — **${d.retained}** retained`);

      const embed = new EmbedBuilder()
        .setColor(config.colors.info)
        .setTitle('📊 Server Invite Tracker — Totals')
        .addFields(
          { name: '📨 Total Tracked',   value: `${all.length}`,                               inline: true },
          { name: '✅ Retained',         value: `${all.filter(e => e.retained).length}`,        inline: true },
          { name: '❌ Lost',             value: `${all.filter(e => e.leftAt && !e.retained).length}`, inline: true },
          { name: '⏳ Pending',          value: `${all.filter(e => !e.retained && !e.leftAt).length}`, inline: true },
          { name: '🏆 Top Inviters by Retention',
            value: top5.length > 0 ? top5.join('\n') : 'No data yet.', inline: false },
        )
        .setTimestamp();
      return interaction.reply({ embeds: [embed], flags: MessageFlags.Ephemeral });
    }

    // ── reset ────────────────────────────────────────────────────
    if (sub === 'reset') {
      const target = interaction.options.getUser('user');
      const embed = new EmbedBuilder()
        .setColor(config.colors.error)
        .setTitle('⚠️ Confirm Invite Reset')
        .setDescription(
          `This will permanently delete all invite records generated by <@${target.id}>.\nThis cannot be undone.`
        )
        .setTimestamp();
      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId(`invitereset:${target.id}`)
          .setLabel('Confirm Reset')
          .setStyle(ButtonStyle.Danger)
      );
      return interaction.reply({ embeds: [embed], components: [row], flags: MessageFlags.Ephemeral });
    }

    // ── export ───────────────────────────────────────────────────
    if (sub === 'export') {
      const buf = Buffer.from(JSON.stringify(invites, null, 2));
      const attachment = new AttachmentBuilder(buf, { name: 'invites.json' });
      return interaction.reply({ content: '📎 Current `invites.json`:', files: [attachment], flags: MessageFlags.Ephemeral });
    }
  },
};
