const { SlashCommandBuilder, PermissionFlagsBits, MessageFlags } = require('discord.js');
const { postListing, LISTING_TYPES } = require('../../utils/postListing');
const config = require('../../config.json');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('showcase-test')
    .setDescription('Owner only: push a fake listing through the real showcase pipeline.')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addStringOption(o => o
      .setName('type')
      .setDescription('Listing type to test')
      .setRequired(true)
      .addChoices(
        ...Object.keys(LISTING_TYPES).map(t => ({ name: t, value: t }))
      )),

  async execute(interaction) {
    if (interaction.user.id !== interaction.guild.ownerId) {
      return interaction.reply({
        content: '<:circlex:1507191508657508503> Only the server owner can run showcase tests.',
        flags: MessageFlags.Ephemeral,
      });
    }

    const type = interaction.options.getString('type');
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    const fakeListing = {
      id: `test-${Date.now()}`,
      type,
      title: `[TEST] Showcase Pipeline — ${type}`,
      shortDescription: 'This is a test listing generated by /showcase-test. It went through the exact same pipeline as real website listings (postListing → forum thread → dedup insert → activity log). Safe to delete.',
      authorUsername: interaction.user.username,
      authorAvatarUrl: interaction.user.displayAvatarURL(),
      thumbnailUrl: config.branding.thumbnail,
      url: config.website,
      createdAt: new Date().toISOString(),
    };

    const result = await postListing(interaction.client, type, fakeListing);

    if (!result.ok) {
      return interaction.editReply({
        content: `<:circlex:1507191508657508503> Test failed: ${result.error}`,
      });
    }

    return interaction.editReply({
      content: `<:circlecheck:1507191508066107532> Test listing posted — thread <#${result.threadId}> (dedup id \`${fakeListing.id}\` recorded).`,
    });
  },
};
