const { SlashCommandBuilder, PermissionFlagsBits, MessageFlags } = require('discord.js');
const { LISTING_TYPES } = require('../../utils/postListing');
const { postListingForReview } = require('../../utils/moderationListing');
const config = require('../../config.json');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('showcase-test')
    .setDescription('Owner only: push a fake listing into the moderation review flow.')
    .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
    .addStringOption(o => o
      .setName('type')
      .setDescription('Listing type to test')
      .setRequired(true)
      .addChoices(
        ...Object.keys(LISTING_TYPES).map(t => ({ name: t, value: t }))
      )),

  async execute(interaction) {
    if (interaction.user.id !== interaction.guild.ownerId) {
      return interaction.reply({
        content: '<:circlex:1507191508657508503> Only the server owner can run showcase tests.',
        flags: MessageFlags.Ephemeral,
      });
    }

    const type = interaction.options.getString('type');
    await interaction.deferReply({ flags: MessageFlags.Ephemeral });

    // `test-` ids skip website API sync in the approve/deny handlers, so the
    // whole moderation flow is testable without the website running.
    const fakeListing = {
      id: `test-${Date.now()}`,
      type,
      title: `[TEST] Moderation Pipeline — ${type}`,
      shortDescription: 'This is a test listing generated by /showcase-test. It went through the exact same pipeline as real website listings (moderation review card → Approve/Deny → public forum post + DM). Safe to delete.',
      fullDescription: 'Full description example: approving this posts it to the public forum for its type and DMs the submitter (you). Denying opens the reason modal and DMs the denial. Website sync is skipped for test listings.',
      authorUsername: interaction.user.username,
      authorAvatarUrl: interaction.user.displayAvatarURL(),
      thumbnailUrl: config.branding.thumbnail,
      submitterDiscordId: interaction.user.id,
      url: config.website,
      createdAt: new Date().toISOString(),
    };

    const result = await postListingForReview(interaction.client, fakeListing);

    if (!result.ok) {
      return interaction.editReply({
        content: `<:circlex:1507191508657508503> Test failed: ${result.error}`,
      });
    }

    return interaction.editReply({
      content: `<:circlecheck:1507191508066107532> Test listing posted for review — moderation thread <#${result.threadId}> (id \`${fakeListing.id}\`). Approve/Deny it there; you are the submitter, so DMs go to you.`,
    });
  },
};
